numeric_vector <- c(1.5, 2.3, 3.7)
character_vector <- c("apple", "banana", "cherry")
logical_vector <- c(TRUE, FALSE, TRUE)
print("Numeric Vector:")
print(numeric_vector)
print("Character Vector:")
print(character_vector)
print("Logical Vector:")
print(logical_vector)
print(paste("Type of Numeric Vector:", class(numeric_vector)))
print(paste("Type of Character Vector:", class(character_vector)))
print(paste("Type of Logical Vector:", class(logical_vector)))
